project_prompt = """
You are working on codesitter. Before making any changes:
1. Review the existing code structure
2. Follow the established patterns and naming conventions
3. Run build after significant changes
4. do not commit changes
"""


[commands]
run = ["codesitter"]  # This allows you to pass any arguments dynamically
custom = ["codesitter"]  # This allows you to pass any arguments dynamically

