project_prompt = """
You are working on codesitter. Before making any changes:
1. Review the existing code structure
2. Follow the established patterns and naming conventions
3. Run build after significant changes
4. do not commit changes
"""


[commands]
analyze = ["codesitter", "analyze","file", "test_calls.ts", "--json"]

